---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    deployment: ods-ci
  name: ods-ci
spec:
  parallelism: 90
  completions: 90
  activeDeadlineSeconds: 18000
  backoffLimit: 15
  completionMode: "Indexed"
  template:
    metadata:
      name: ods-ci-loadtest
    spec:
      containers:
        - image: registry.redhat.io/ubi8/ubi
          command: [sleep, "60"]
          #imagePullPolicy: Always
          name: ods-ci
      restartPolicy: Never
