---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmarking-coco-dataset
  namespace: matrix-benchmarking
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
