apiVersion: v1
data:
  entrypoint.sh: |
    #!/bin/bash

    set -o pipefail
    set -o errexit
    set -o nounset

    set -x

    cd /tmp
    cp /gpu-burn-src/* .

    make

    echo ""
    echo "Running GPU Burn for ${GPU_BURN_TIME} seconds."
    time ./gpu_burn $GPU_BURN_TIME
kind: ConfigMap
metadata:
  name: gpu-burn-entrypoint
