---
apiVersion: v1
kind: Pod
metadata:
 name: transformer-xl-download-data
 namespace: matrix-benchmarking
spec:
  containers:
  - name: cnt
    image: image-registry.openshift-image-registry.svc:5000/matrix-benchmarking/aiml:transformer-xl
    command: [ "bash", "-ceuxo", "pipefail"]
    args:
    - |
      if [ "$(ls data)" ]; then
        echo "Data directory not empty, skipping."
        ls data
        exit 0
      fi
      bash -x /workspace/examples/transformer-xl/getdata.sh
    volumeMounts:
    - mountPath: /workspace/transformer-xl/pytorch/data
      name: storage-volume
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: benchmarking-transformer-xl-dataset
  restartPolicy: Never
