---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmarking-dlrm-dataset
  namespace: matrix-benchmarking
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
  storageClassName: efs-csi-sc
